# Generated by Django 5.2.2 on 2025-06-07 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('org', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('referral_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active_investment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('has_invested', models.BooleanField(default=False)),
                ('notify_earnings', models.BooleanField(default=True)),
                ('notify_new_plans', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('phone_confirmed', models.BooleanField(default=False)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('is_banned', models.BooleanField(default=False)),
                ('login_attempts', models.PositiveIntegerField(default=0)),
                ('account_type', models.CharField(choices=[('free', 'Free'), ('investor', 'Investor'), ('admin', 'Admin')], default='free', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('signup_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signup_device', models.CharField(blank=True, max_length=255, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('last_phone_update', models.DateTimeField(blank=True, null=True)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['referral_code'], name='user_profil_referra_0fd1d8_idx'), models.Index(fields=['phone'], name='user_profil_phone_0e28bf_idx')],
            },
        ),
    ]
