# Generated by Django 5.2.2 on 2025-06-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_avatar_profile_browser_profile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gcash_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='maya_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_payment',
            field=models.CharField(choices=[('gcash', 'GCash'), ('maya', 'Maya'), ('both', 'GCash & Maya')], default='gcash', max_length=10),
        ),
    ]
