# Generated by Django 5.2.2 on 2025-06-07 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_gcash_number_profile_maya_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('reason_choice', models.CharField(choices=[('multiple_accounts', 'Multiple Accounts'), ('fraud', 'Fraudulent Activity'), ('abuse', 'Platform Abuse'), ('kyc_violation', 'KYC Violation'), ('spamming', 'Spamming/Advertising'), ('other', 'Other (custom reason below)')], default='other', max_length=30)),
                ('custom_reason', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banned_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('blocked_until', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='BlacklistedIP',
        ),
    ]
