# Generated by Django 5.2.2 on 2025-06-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_bannedaccount_blockedip_delete_blacklistedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login_device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
