# Generated by Django 5.2.2 on 2025-06-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_loginhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
