# Generated by Django 5.2.2 on 2025-06-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
