# Generated by Django 5.2.2 on 2025-06-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='investment_goal',
            field=models.DecimalField(decimal_places=2, default=100000.0, help_text='Target investment goal set by the user', max_digits=12),
        ),
    ]
