# Generated by Django 5.2.2 on 2025-06-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_profile_investment_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='is_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='was_successful',
            field=models.BooleanField(default=False),
        ),
    ]
