# Generated by Django 5.2.2 on 2025-06-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_loginhistory_is_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kyc_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='unverified', max_length=10),
        ),
    ]
