# Generated by Django 5.2.2 on 2025-06-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_profile_kyc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_payment',
            field=models.CharField(choices=[('gcash', 'GCash'), ('maya', 'Maya'), ('both', 'GCash & Maya')], default='gcash', max_length=10, null=True),
        ),
    ]
