# Generated by Django 5.2.2 on 2025-06-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_profile_first_name_alter_profile_gcash_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
